export default {
    google: {
        gtmWidgetUrl: new URL(`https://www.googletagmanager.com/gtag/js`),
        gtmNoScriptUrl: new URL(`https://www.googletagmanager.com/ns.html`),
    },
    mailchimp: {
        subscribeUrl: new URL(`https://${process.env.MAILCHIMP_COMPANY}.${process.env.MAILCHIMP_SERVER}.list-manage.com/subscribe/post-json`),
    },
    intakeq: {
        widgetUrl: new URL('https://intakeq.com/js/widget.min.js?1'),
    },
    geoPlugin: {
        url: new URL('http://www.geoplugin.net/json.gp?'),
    },
    termly: {
        embedUrl: new URL('https://app.termly.io/embed-policy.min.js'),
    },
    usRegions: [
        'Alabama',
        'Alaska',
        'Arizona',
        'Arkansas',
        'California',
        'Colorado',
        'Connecticut',
        'Delaware',
        'Florida',
        'Georgia',
        'Hawaii',
        'Idaho',
        'Illinois',
        'Indiana',
        'Iowa',
        'Kansas',
        'Kentucky',
        'Louisiana',
        'Maine',
        'Maryland',
        'Massachusetts',
        'Michigan',
        'Minnesota',
        'Mississippi',
        'Missouri',
        'Montana',
        'Nebraska',
        'Nevada',
        'New Hampshire',
        'New Jersey',
        'New Mexico',
        'New York',
        'North Carolina',
        'North Dakota',
        'Ohio',
        'Oklahoma',
        'Oregon',
        'Pennsylvania',
        'Rhode Island',
        'South Carolina',
        'South Dakota',
        'Tennessee',
        'Texas',
        'Utah',
        'Vermont',
        'Virginia',
        'Washington',
        'West Virginia',
        'Wisconsin',
        'Wyoming',
        'District of Columbia',
        'Puerto Rico',
      ],
}