import { blue, green, purple, red } from '@mui/material/colors';
import { LoremIpsum } from "lorem-ipsum";

export default {
  name: 'Telemedica',
  defaultPageTitle: '#1 Telehealth Platform for Veterans | Nexus Letter Experts',
  url: 'https://telemedicallc.com',
  company: 'Telemedica LLC',
  copyrightYearInitial: 2023,
  social: [
    'https://www.facebook.com/telemedicallc',
    'https://instagram.com/telemedicallc',
    'https://www.linkedin.com/company/telemedica-llc/',
    'https://www.youtube.com/channel/UCoqOPabfIAlkDy9XjTGsb0Q',
  ],
  contact: {
    phone: '+15128838446',
    email: 'mailto:email@email.com',
  },
  articleTagColors: {
    'nexus-letter': red[400],
    'mental-health': blue[300],
    'physical-conditions': green[400],
    'veteran-resources': purple[400],
  },
  externalLinks: {
    patientPortal: 'https://telemedicallc.intakeq.com/portal',
    helpDesk: 'https://help.telemedicallc.com/',
    providerPortal: 'https://intakeq.com/',
  },
  // googleAnalyticsId: 'G-73TKHSVTNZ',
  dummyText: new LoremIpsum({
    sentencesPerParagraph: {
      max: 8,
      min: 4
    },
    wordsPerSentence: {
      max: 16,
      min: 4
    }
  }),
  newsletter: {
    listId: '08b1d97e11',
    tags: ['website', 'newsletter'],
  },
  bookingForms: {
    'Alabama': '1',
    // 'Alaska': '0',
    // 'Arizona': '0',
    // 'Arkansas': '0',
    // 'California': '0',
    'Colorado': '2',
    // 'Connecticut': '0',
    // 'Delaware': '0',
    // 'Florida': '0',
    // 'Georgia': '0',
    // 'Hawaii': '0',
    // 'Idaho': '0',
    // 'Illinois': '0',
    // 'Indiana': '0',
    // 'Iowa': '0',
    // 'Kansas': '0',
    // 'Kentucky': '0',
    // 'Louisiana': '0',
    // 'Maine': '0',
    // 'Maryland': '0',
    // 'Massachusetts': '0',
    // 'Michigan': '0',
    // 'Minnesota': '0',
    // 'Mississippi': '0',
    // 'Missouri': '0',
    // 'Montana': '0',
    // 'Nebraska': '0',
    // 'Nevada': '0',
    // 'New Hampshire': '0',
    // 'New Jersey': '0',
    // 'New Mexico': '0',
    // 'New York': '0',
    // 'North Carolina': '0',
    // 'North Dakota': '0',
    // 'Ohio': '0',
    // 'Oklahoma': '0',
    // 'Oregon': '0',
    // 'Pennsylvania': '0',
    // 'Rhode Island': '0',
    // 'South Carolina': '0',
    // 'South Dakota': '0',
    // 'Tennessee': '0',
    'Texas': '3',
    // 'Utah': '0',
    // 'Vermont': '0',
    // 'Virginia': '0',
    // 'Washington': '0',
    // 'West Virginia': '0',
    // 'Wisconsin': '0',
    // 'Wyoming': '0',
    // 'District of Columbia': '0',
    // 'Puerto Rico': '0',
    // 'Guam': '0',
    // 'American Samoa': '0',
    // 'U.S. Virgin Islands': '0',
    // 'Northern Mariana Islands': '0',
  }
}